config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # verb 'path', to: 'controller#action', as: :custom_prefix
  get '/about', to: 'pages#about', as: :about_us
  get '/contact', to: 'pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @date = Date.today.strftime('%A, %b %d')
  end

  def about
  end

  def contact
    query = params[:query]
    @members = %w[Andrew Anabelle Lisandra Reed]

    if query.present?
      @members = @members.select { |member| member.start_with?(query) }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsIntro1038</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div style="background: lightcoral; padding: 16px" >
      A Navbar
      <span><%= link_to 'Home 🏠', root_path %></span>
      <span><%= link_to 'About Us 👯‍♂️', about_us_path %></span>
      <span><%= link_to 'Contact ☎️', contact_path %></span>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem, voluptate velit. Recusandae, iste voluptatibus? Voluptatem consectetur, quidem, ex commodi aut veniam hic saepe, beatae autem ullam earum. Fugiat, ipsa iure!</p>

app/views/pages/contact.html.erb
<h1>Meet the team!</h1>

<p>
  The following will not be displayed: <% 'this will not be displayed' %>
</p>
<p>See, told you 😄</p>

<p>
  This will, though: <%= 'this will be displayed' %>
</p>

<form action="/contact" method="get">
  <input type="text" name="query" placeholder="Who are you looking for?" value="<%= params[:query] %>">
  <input type="submit">
</form>

<ul>
  <% @members.each do |member| %>
    <li><%= member %></li>
  <% end %>
</ul>

app/views/pages/home.html.erb
<h1>Welcome to our website!</h1>

<p>Today is <strong><%= @date %></strong></p>

<%= link_to contact_path do %>
  <%= image_tag 'deadpool.png', width: 200 %>
<% end %>